### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by blp73** [kerryjiang/SuperSocket#109]
Hi,

We are using 1.6.6.0 and have about 1000 clients connected and process about 12 requests a second. Once every 3-4 weeks, the application crashes with the below error message. Any ideas as to what can be done to fix it?

2017-05-29 12:16:12,917 [5164] ERROR DefaultBootstrap - The process crashed for an unhandled exception!
System.InvalidOperationException: "An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.";
   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Sockets.SocketAsyncEventArgs.SetBuffer(Int32 offset, Int32 count)
   at SuperSocket.SocketEngine.AsyncSocketServer.SessionClosed(ISocketSession session, CloseReason reason)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at SuperSocket.SocketEngine.SocketSession.OnClosed(CloseReason reason)
   at SuperSocket.SocketEngine.AsyncSocketSession.OnClosed(CloseReason reason)
   at SuperSocket.SocketEngine.SocketSession.InternalClose(Socket client, CloseReason reason, Boolean setCloseReason)
   at SuperSocket.SocketEngine.SocketSession.OnSendEnd(Boolean isInClosingOrClosed)
   at SuperSocket.SocketEngine.SocketSession.OnSendingCompleted(SendingQueue queue)
   at SuperSocket.SocketEngine.AsyncSocketSession.OnSendingCompleted(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object ignored)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

Thank You

**Comment by kerryjiang** [comment]
Could you try 1.6.6.1? I remember there was a fix about this issue in this release.

**Comment by blp73** [comment]
Hi,

Thank you for the response, we updated to 1.6.7 this morning. Hopefully that will resolve it.

Thanks

**Comment by blp73** [comment]
Hi, We updated to 1.6.7 and the error occurred again today. Any thoughts on what is happening? Maybe that would let us reproduce it and fix it?

Thanks
