### ISSUE TITLE
Async problem in .Net 2 when proxy s used

### ISSUE THREAD

**Issue by GeKoMi** [kerryjiang/SuperSocket#126]
I got some times this error during a websocket connection behind a proxy:

System.InvalidOperationException: EndResolve can only be called once for each asynchronous operation.
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.ConnectAsyncExtension.OnGetHostAddresses(IAsyncResult result)

I Have foud the Problem in: ..\SuperSocket.ClientEngine\Common\ConnectAsyncExtension.Net.cs
in Line 46:
```
if (asyncResult.CompletedSynchronously)
    OnGetHostAddresses(asyncResult);
```
it should be
```
if (**!**asyncResult.CompletedSynchronously)
    OnGetHostAddresses(asyncResult);
```

Regards Gerhard

**Comment by GeKoMi** [comment]
No this has also not solved the problem  ;)
removing this two lines helps. But can you check what the correct solution is?
thx Gerhard

**Comment by kerryjiang** [comment]
In my opinion, it is the correct logic:

if (asyncResult.CompletedSynchronously)
    OnGetHostAddresses(asyncResult);
