### ISSUE TITLE
Appserver.Start() fail to start on Linux (Ubuntu 16.04) with .NetCore 2.1 runtime

### ISSUE THREAD

**Issue by 41m4n** [kerryjiang/SuperSocket#163]
My finding leads to this discussion below due to the issue
[https://github.com/dotnet/corefx/issues/11292#issuecomment-243850368](https://github.com/dotnet/corefx/issues/11292#issuecomment-243850368)

`Console.WriteLine("Press any key to start the server!");

            Console.ReadKey();
            Console.WriteLine();
            
            var appServer = new AppServer();
            appServer.NewSessionConnected += new SessionHandler<AppSession>(appServer_NewSessionConnected);
            
            //Setup the appServer
            if (!appServer.Setup(34321)) //Setup with listening port
            {
                Console.WriteLine("Failed to setup!");
               
                Console.ReadKey();
                return;
            }

            Console.WriteLine();

            //Try to start the appServer
            try
            {
                if (!appServer.Start())
                {
                    Console.WriteLine("Failed to start!");
                    Console.ReadKey();
                    return;
                }
            }`

i tried this sample code built using Visual Studio 2017. It runs successfully on Windows.
After it is published and ran  on linux-arm. it gives following error . SuperSocket (1.6.6.1)

`2018-08-10 03:46:46,255 [1] ERROR AppServer-15368010 - Listener (0.0.0.0:34321) error: Operation not supported
System.Net.Sockets.SocketException (95): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Boolean optionValue)
   at SuperSocket.SocketEngine.TcpAsyncSocketListener.Start(IServerConfig config)
2018-08-10 03:46:46,618 [1] ERROR AppServer-15368010 - Listener (0.0.0.0:34321) error: Address already in use
System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at SuperSocket.SocketEngine.TcpAsyncSocketListener.Start(IServerConfig config)`

**Comment by chucklu** [comment]
What's the version of SuperSocket you are using?

**Comment by 41m4n** [comment]
supersocket 1.6.6.1
supersocket.engine 1.6.6.1
log4net 2.0.3

**Comment by chucklu** [comment]
why you mentioned an issue from corefx ?
The .net core version of SuperSocket is still under the development on branch master.
The version 1.6 is not .net core version

**Comment by 41m4n** [comment]
My apology...it means that latest SuperSocket (1.6)  does not support .netcore yet?...So i need to wait for the release first or you have any recommendation ?

**Comment by chucklu** [comment]
I remember the version 1.6 support mono.
You can read this documentation [Run SuperSocket in Linux/Unix](http://docs.supersocket.net/v1-6/en-US/Run-SuperSocket-in-Linux-Unix).

About .net core version, you can check the conversation in this issue https://github.com/kerryjiang/SuperSocket/issues/123

**Comment by 41m4n** [comment]
Thanks for your time...great work
