### ISSUE TITLE
Websocket Server closes session with large packet on SendAsync

### ISSUE THREAD

**Issue by mago-pablo** [kerryjiang/SuperSocket#286]
Using the sample websocket server adding the following options in appsettings: 
"maxPackageLength": 10240,
"receiveBufferSize": 12240,
"sendBufferSize": 12240,
 "receiveTimeout": 60000,
"sendTimeout": 60000,

I have a client the sends the following packet to replicate the error: 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" 

The session immediately closes after the send with the following error: 

On server:
```
fail: IChannel[0]
      Exception happened in ReceiveAsync
System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at SuperSocket.Channel.TcpPipeChannel`1.ReceiveAsync(Socket socket, Memory`1 memory, SocketFlags socketFlags) in ...\SuperSocket.Channel\TcpPipeChannel.cs:line 43
   at SuperSocket.Channel.TcpPipeChannel`1.FillPipeWithDataAsync(Memory`1 memory) in ...\SuperSocket.Channel\TcpPipeChannel.cs:line 38
   at SuperSocket.Channel.PipeChannel`1.FillPipeAsync(PipeWriter writer) in ...SuperSocket.Channel\PipeChannel.cs:line 105
```
On Client
```
Unhandled exception. System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at ....Program.Main(String[] args) in ...\Program.cs:line 81
   at ....Program.<Main>(String[] args)
```

If I shorten the message the error does not happen. And if I change the server settings it does not seem to help, am I configuring wrong the server? or is this a bug derived from packet length. 

I originally got the bug from using it as a chat server. 

Kind regards.

**Comment by kerryjiang** [comment]
This bug has been fixed by the latest commit.

**Comment by mago-pablo** [comment]
I have tested with the original project detected the issue, and it worked perfectly, thank you very much for such a quick response.
