### ISSUE TITLE
System.NullReferenceException:“Object reference not set to an instance of an object.”

### ISSUE THREAD

**Issue by fendou** [kerryjiang/SuperSocket#300]
System.NullReferenceException:“Object reference not set to an instance of an object.”
运行WebSocketServer示例，过了一会儿就弹出这个错误了。
![Snipaste_2020-03-22_18-54-21](https://user-images.githubusercontent.com/502932/77247811-82cf1300-6c6f-11ea-9b5f-46c01755e4e0.png)

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SuperSocket.WebSocket
  StackTrace:
   at SuperSocket.WebSocket.WebSocketEncoder.Encode(IBufferWriter`1 writer, WebSocketMessage pack)
   at SuperSocket.Channel.PipeChannel`1.WritePackageWithEncoder[TPackage](PipeWriter writer, IPackageEncoder`1 packageEncoder, TPackage package)
   at SuperSocket.Channel.PipeChannel`1.<SendAsync>d__41`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at WebSocketServer.Program.<>c.<<Main>b__0_0>d.MoveNext() in E:\SuperSocket-master\samples\WebSocketServer\Program.cs:line 17

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    WebSocketServer.Program.Main.AnonymousMethod__0_0(SuperSocket.WebSocket.Server.WebSocketSession, SuperSocket.WebSocket.WebSocketPackage) (位于 Program.cs 中)

**Comment by kerryjiang** [comment]
你用哪个版本？客户端是怎么跑的？

**Comment by fendou** [comment]
用的是2.0.0-preview3-01，从nuget安装最新版supersocket,直接示例websocketserver点运行,刚开始还好，但是过了一会儿就报错了.客户端是百度搜索到的，叫 WebSocket客户端测试工具 v4.20免费版和websocketman， http://www.pc6.com/softview/SoftView_570960.html
https://blog.csdn.net/openownworld/article/details/95178583

**Comment by kerryjiang** [comment]
"直接示例websocketserver点运行"? 这个是啥意思？你不是说用的nuget包吗？

**Comment by fendou** [comment]
sample中没有引用supersocket项目源码，有
![Snipaste_2020-03-23_11-01-15](https://user-images.githubusercontent.com/502932/77276477-be142500-6cf5-11ea-9161-9a6a245bcc35.png)
依赖包啊

**Comment by fendou** [comment]
> "直接示例websocketserver点运行"? 这个是啥意思？你不是说用的nuget包吗？

![Snipaste_2020-03-23_11-03-20](https://user-images.githubusercontent.com/502932/77276547-f156b400-6cf5-11ea-90c0-6c8e946a009a.png)

**Comment by kerryjiang** [comment]
SuperSocket.WebSocket.Server那个引用怎么是dll？

**Comment by kerryjiang** [comment]
I will try to reproduce it.

**Comment by fendou** [comment]
> I will try to reproduce it.

I think it's an error connection in 60 seconds.

**Comment by kerryjiang** [comment]
Just tested with https://www.websocket.org/echo.html, and it worked fine.

"I think it's an error connection in 60 seconds.", it seems like no handshake happened. Is it a standard websocket client?

**Comment by kerryjiang** [comment]
I think this issue has been fixed by recent changes.
