### ISSUE TITLE
wss crash

### ISSUE THREAD

**Issue by imtrobin** [kerryjiang/SuperSocket#311]
Hi, reporting the sample websocket crash when using wss to connect

e.g
wss://192.168.1.99:4041
Crash

```
TcpChannelCreator[0]
      Failed to create channel for 192.168.1.99:58228.
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at SuperSocket.Server.TcpChannelCreatorFactory.<>c__DisplayClass3_0`1.<<CreateChannelCreator>b__1>d.MoveNext() in D:\Dev\GAMECLOUD\CODE\external\backend\SuperSocket\src\SuperSocket.Server\TcpChannelCreatorFactory.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by kerryjiang** [comment]
It seems not a crash. The server still can accept new connections even if the exception happen.
The error may be related with the certificate. But it cannot be reproduced by test cases.
