### ISSUE TITLE
TLS1.3 with Firefox error

### ISSUE THREAD

**Issue by lw364** [kerryjiang/SuperSocket#347]
In Firefox set 
security.tls.version.min=4

In SuperSocket Server part set 

      The listener [Ip=Any, Port=20708, Security=Tls12, Tls13, Path=, BackLog=0, NoDelay=False] has been started.

Try action wss://serverip:20708

Got error

fail: TcpChannelCreator[0]
      Failed to create channel for Clientip .
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090331): The client and server cannot communicate, because they do not possess a common algorithm.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at SuperSocket.Server.TcpChannelCreatorFactory.<>c__DisplayClass3_0`1.<<CreateChannelCreator>b__1>d.MoveNext() in C:\Projects\SuperSocket\src\SuperSocket.Server\TcpChannelCreatorFactory.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at SuperSocket.Server.TcpChannelCreator.OnNewClientAccept(Socket socket) in C:\Projects\SuperSocket\src\SuperSocket.Server\TcpChannelCreator.cs:line 134

--

**Comment by lw364** [comment]
If n Firefox set  security.tls.version.min=3
Do same action above:  wss://serverip:20708
Server log:
      A new session connected: e6cd905d-f43d-455d-96c5-8430160c547a

**Comment by lw364** [comment]
Just wonder current SuperSocket does not support  TLS1.3 or My Cert files not for TLS1.3?

**Comment by kerryjiang** [comment]
I think it is supported. I will have a try.

**Comment by kerryjiang** [comment]
Could you check if your system supports TLS 1.3?

**Comment by lw364** [comment]
Right. My windows server not set for tls 1.3. Thanks.
