### ISSUE TITLE
[WebSocket Server] Getting "Clear idle session error!" continously in random time.

### ISSUE THREAD

**Issue by a6387534** [kerryjiang/SuperSocket#417]
Hello, I am getting "Clear idle session error!" continuously in random time. (SuperSocket v1.6.6.1 + WebSocket Server).

This problem usually happens when the server has >450 clients and after the server run for few hours.

There is the error screenshot:
![image](https://user-images.githubusercontent.com/49149001/97018415-b6657900-1581-11eb-8c02-0bcaa297f1ac.png)

Before this message is printed, there are lots of message "The session will be closed for XXXX timeout..." printed in the log.

WebSocket Server Config:

```
            config.Port = 1234;
            config.Ip = "Any";
            config.Mode = SocketMode.Tcp;
            config.MaxConnectionNumber = 5000;
            config.ReceiveBufferSize = 65535;
            config.SendBufferSize = 524289;

            config.IdleSessionTimeOut = 35;
            config.ClearIdleSession = true;
            config.ClearIdleSessionInterval = 35;

            config.KeepAliveTime = 60;
            config.KeepAliveInterval = 10;
            config.SendTimeOut = 8192;

```

Also notice that:
1. I have frequently data transferring between server and clients.
2. SQL queries were done after a new client connects
3. More clients has higher chance to trigger the error
4. When this error happen, there are some clients kept connected to the WebSocket server (I figured out it by printing SessionCount). (Is it possible the server not able to kill the timed out client instance?)
5. High memory usage when this error happen.

**Comment by kerryjiang** [comment]
Which kind of WebSocket server do you use? SuperWebSocket or SuperSocket.WebSocket?

Anyway, I would suggest you to upgrade SuperSocket 2.0.

**Comment by a6387534** [comment]
I am using SuperSocket.WebSocket v1.6.6.1 downloaded in nuget.

Did SuperSocket 2.0 solve this problem?

**Comment by AlexLein** [comment]
I am also on 1.6.6.1 from the Nuget package.

I am also seeing this when I have lots (>400) of active sessions.  I also see the number of Handles increasing constantly (specifically handles for "\Device\Afd" which is a socket handle).

Before I spend a lot of time upgrading to the 2.0 branch, is there a way to increase the amount of time SuperSocket waits trying to idle sockets?

**Comment by a6387534** [comment]
I found another interesting fact is that it is more likely to be happened when the server PC having cpu usage >60%

**Comment by AlexLein** [comment]
I've made a change to the config of my instance:

I added `clearIdleSessionInterval="10"` to the `<server/>` element.  The default session snapshot interval is 5 seconds, so I figured it would be ok.  I will report back on whether or not my handles increase over the course of a week.

My new hypothesis is that idle sessions are being killed at the firewall, and when that happens, the regular cleanup routine throws an exception trying to cleanup after the socket.  Specifically, there's not try/catch in the cleanup routine on a per session call.  So if you have many sockets to close due to idling, the `Parallel.ForEach` will throw an AggregateException on one of the first sessions it's trying to close, and they rest are not acted upon.

I still see "Clear idle session error!" messages, but I also see them skipping a 10 second interval, meaning that the socket did get closed (somehow) and it performed the clear-idle operation again without the troublemaker session(s).  If my config doesn't fix the issue, then fixing the code should be a matter of adding an inner try/catch into `ClearIdleSession` in `\SuperSocket\SocketBase\AppServer.cs`.

**Comment by a6387534** [comment]
@AlexLein 
Have you ever encountered "The sending attempt timed out" error while you are trying to send data to clients?
I encountered it usually when I set ClearIdleSession as false. 

I also tried to increase SendingQueueSize to 100 (default was 5), this error was disappeared but the memory usage increases incredibly (5-20 GB for single process). My hypothesis is that the server keep sending data to client(s) but data just stuck in sending queue for some reason (possibly there is a troublemaker session which makes the data cannot be sent out.?)

I have tried to reduce the server CPU usage (i.e. <30%) and kept same amount of clients, the error disappeared somehow.

**Comment by AlexLein** [comment]
@a6387534 
I got around that error by creating my own "outgoing messages" queue, and switching to `session.TrySend`.  If the result is false, then the session's internal message system is full or incapable of sending at that moment, so I add the message into a "retry" queue; after 10 retries it fails permanently and the message is dropped.  I have my `receiveBufferSize` and `sendBufferSize` set to `65536`, but SendingQueueSize is not defined (so default).

**Comment by AlexLein** [comment]
I have successfully made the problem worse!
What used to take the better part of a month has been accomplished in just 6 days; I have over 100k handles.

I will try setting the `clearIdleSessionInterval="300"` and will report again in a week on my handle count.

**Comment by kerryjiang** [comment]
@a6387534 @AlexLein 

Sorry, SuperSocket 1.6.* is out of maintenance.
I would suggest you upgrade to SuperSocket 2.0. And 2.0 would not have this kind of problems. If it happens to you even after you upgrade, I will investigate the issue and fix it ASAP.

**Comment by AlexLein** [comment]
Thanks @kerryjiang, but 2.0 is still in "beta", contains **all the breaking changes**, and would be a huge effort to update for a _possible_ (not guaranteed) fix.  We are still on .NET Framework v4.6.2 too...

I can read the code and I will try to puzzle it out myself.  My other suspicion is that trying to send data to a disconnected session (one killed by the firewall and not by the client or server themselves) is a possible source of the leak.

If all that fails, I will start work on a 2.0beta7 branch for my own project, and may god have mercy on my soul.

**Comment by kerryjiang** [comment]
Understand.

I should be able to take a look at the legacy code and give you some suggestions.

**Comment by kerryjiang** [comment]
Could you try this fix?
https://github.com/kerryjiang/SuperSocket/commit/e82c313c52885d6b09e5ecf1fc81c7006b8b4366

**Comment by AlexLein** [comment]
Thanks!  I will let my service run until Friday and check the handles.  If it's around 100k, I will know that the clear idle session process is not responsible.

**Comment by kerryjiang** [comment]
@AlexLein any update about this issue?

**Comment by AlexLein** [comment]
Hi @kerryjiang, thank you for reminding me.  Well, my service is at 93k handles now, and probably over 100k tomorrow.
So the clear idle session timeout is probably a _symptom_, and **not the cause**.
This contradicts my previous statement where I thought I had made the problem worse by setting the timeout to 10s instead of 120s.

I've done a bit more digging and I think I can rule out code changes from my own team.  The first instance of handle overload was in June, and since then it has only crashed one other time.  We had not made any changes to the communication layer code since February; and even then it was simply a new try/catch for the command pipeline.

I also setup a new instance and ran a connect/disconnect routine that ran every one second, and that instance never had an issue with handles.

I have noticed that I end up with multiple sockets with outgoing messages that never go out, similar to @a6387534 was talking about. I don't think that the `.TrySend` or `.Send` is the problem though, I think that there is something else underlying that is playing havoc with session disposal.  From what I can tell, my own internal "retry send" queue builds up messages for only one or two sessions, and then after ten retries, it just gives up.  I think those sessions are the one's not being disposed of properly... somehow...

I have a sprint to get done this week, but I will start fresh on this issue Monday.  The first thing I will be looking at is these entries in the error log:
```
2020-11-18 00:00:05,108 [224] ERROR KrakenServer - Session: fa18f97d-9bee-43e5-9d51-e426d3719a65/199.167.34.4:7563
Unexpected error
Caller: OnBeginInitStream, file path: d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncStreamSocketSession.cs, line number: 255
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.SocketEngine.AsyncStreamSocketSession.OnBeginInitStream(IAsyncResult result, Boolean connect)
2020-11-18 00:00:06,311 [245] ERROR KrakenServer - Session: d2e29e48-ce29-4333-ad50-61066d231c3a/199.167.34.4:32940
Unexpected error
Caller: OnBeginInitStream, file path: d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncStreamSocketSession.cs, line number: 255
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.SocketEngine.AsyncStreamSocketSession.OnBeginInitStream(IAsyncResult result, Boolean connect)
```
Specifically I want to try to correlate those errors' session ids to those in the info logs.

**Comment by AlexLein** [comment]
I think I found some evidence of the leak happening.

Here is an example session `31fb5a7c-9108-4780-b422-80e43ca771ae` that I can find in the info20201118.log file.  (I am pasting in only those lines that deal with this session).
```
2020-11-18 16:29:09,205 [420] INFO  KrakenServer - Session: 31fb5a7c-9108-4780-b422-80e43ca771ae/199.167.34.4:48041
A new session connected!
2020-11-18 16:55:23,614 [215] INFO  KrakenServer - Session: 31fb5a7c-9108-4780-b422-80e43ca771ae/199.167.34.4:48041
The session will be closed for 459.6396696 timeout, the session start time: 11/18/2020 4:29:09 PM, last active time: 11/18/2020 4:47:43 PM!
2020-11-18 17:00:23,641 [151] INFO  KrakenServer - Session: 31fb5a7c-9108-4780-b422-80e43ca771ae/199.167.34.4:48041
The session will be closed for 759.6662693 timeout, the session start time: 11/18/2020 4:29:09 PM, last active time: 11/18/2020 4:47:43 PM!
2020-11-18 17:05:23,624 [122] INFO  KrakenServer - Session: 31fb5a7c-9108-4780-b422-80e43ca771ae/199.167.34.4:48041
The session will be closed for 1059.6489987 timeout, the session start time: 11/18/2020 4:29:09 PM, last active time: 11/18/2020 4:47:43 PM!
... you get the idea...
2020-11-18 20:34:31,372 [288] INFO  KrakenServer - Session: 31fb5a7c-9108-4780-b422-80e43ca771ae/199.167.34.4:48041
This session was closed for SocketError!
```
I also see this session in my own logs regarding the re-try of sending messages where it cannot send, and also gives up after 10 retries.

It also does close _eventually_, so now I need to trace through all sessions to see how many are still being listed as active even when they are not.  I will be adding a command to my service to output details of the sessions that have activity time of over 5 minutes.  If the number continues to increase after invoking it once a day, I will know for sure where the issue lays.  It may also reveal something else like client/browser information that could prove useful.

**Comment by kerryjiang** [comment]
Very useful information.

**Comment by AlexLein** [comment]
Going back as far as Aug 4, I found:
771 sessions that needed to be cleared more than once.
413 of those needed to be cleared more than 10 times.
147 of those needed to be cleared more than 50 times.
93 of those needed to be cleared more than 100 times.
5 of those needed to be cleared more than 1000 times.
(these numbers are a bit off because I was also changing the "clear idle timeout" settings for the last few weeks).

It is my belief that the cause is idle sessions not being disposed of properly, or possibly having multiple references created while working on them.  My server implementation listens for updates from our internal systems, then relays that information to the relevant users/sessions.

My next step is to try tracing through all the places where the session is referenced or created.

**Comment by kerryjiang** [comment]
Aug 4?

**Comment by AlexLein** [comment]
That's just how far back the log files go.

**Comment by AlexLein** [comment]
My experiments continue.

I tried a few more config changes first and what I found was that RAM usage and handle count went up much faster with the GC server `<gcServer enabled="false" />` disabled (we normally have it enabled).  So I re-enabled it.  @a6387534, can you tell me if you have this setting enabled in your config?

Right now I am running with 831910a8 built from source instead of the nuget package.  I will report back with more details next week.

@kerryjiang I was having some difficulty with part of my investigation and maybe you can point me in the correct direction.  I was trying to use my own `CommandLoader` to discover my server's commands, but I wasn't able to.  It seemed to always switch back to the `ReflectCommandLoader`, and it seems that my commands are sub-protocol commands.  So my question is this: is there a way to list the `SubCommandBase<TWebSocketSession>` that I've implemented?

**Comment by a6387534** [comment]
@AlexLein 

I didn't put config xml file when I run the websocket server.  Does it matter?

**Comment by AlexLein** [comment]
Just curious. Trying to find some common elements between our instances to try to pinpoint the root cause of the leak.

By default, the GC server is disabled and garbage collection runs in proc; when enabled runs the GC from a separate CPU.

https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element

**Comment by kerryjiang** [comment]
> My experiments continue.
> 
> I tried a few more config changes first and what I found was that RAM usage and handle count went up much faster with the GC server `<gcServer enabled="false" />` disabled (we normally have it enabled). So I re-enabled it. @a6387534, can you tell me if you have this setting enabled in your config?
> 
> Right now I am running with [831910a](https://github.com/kerryjiang/SuperSocket/commit/831910a8c5a5e8e94a22ecc7ba595855fe0c9331) built from source instead of the nuget package. I will report back with more details next week.
> 
> @kerryjiang I was having some difficulty with part of my investigation and maybe you can point me in the correct direction. I was trying to use my own `CommandLoader` to discover my server's commands, but I wasn't able to. It seemed to always switch back to the `ReflectCommandLoader`, and it seems that my commands are sub-protocol commands. So my question is this: is there a way to list the `SubCommandBase<TWebSocketSession>` that I've implemented?

I think enable logging for Debug would work. Could you try?

**Comment by AlexLein** [comment]
I think you misunderstand me; I'm looking to run a counter on each command to see how often each session invokes the command (and which sessions do) and clear the list on a timer.  I think it will help me identify invalid sessions.

Sessions such as `f270ae44-1ddd-4c0b-9e78-44be358cf326`:
```
2020-12-18 12:54:14,741 [5] INFO  KrakenServer - Session: f270ae44-1ddd-4c0b-9e78-44be358cf326/24.114.88.100:9481
A new session connected!
2020-12-18 13:22:30,101 [296] INFO  KrakenServer - Session: f270ae44-1ddd-4c0b-9e78-44be358cf326/24.114.88.100:9481
The session will be closed for 560.6709595 timeout, the session start time: 12/18/2020 12:54:14 PM, last active time: 12/18/2020 1:13:09 PM!
... and so on...
2020-12-18 16:17:30,682 [259] INFO  KrakenServer - Session: f270ae44-1ddd-4c0b-9e78-44be358cf326/24.114.88.100:9481
The session will be closed for 11061.2518732 timeout, the session start time: 12/18/2020 12:54:14 PM, last active time: 12/18/2020 1:13:09 PM!
```
So, even after updating to 831910a (the latest of the v1.6 commits) to include handling error killing idle sessions, individual bad sessions remain.  I am also hitting about 60,000 handles right now, so I don't think the issue has been resolved with the e82c313 patch.

I am going to write that command to output idle session information now and patch the server early next week so I can get more data about those sessions (or the client being used... I don't think it's a browser).

**Comment by AlexLein** [comment]
Behold, an update!  (After the xmas break I was in dig-out mode and wasn't able to focus on this again until recently.)

I added a command to my server that will output the current details of all sessions (idle or not); and I found one that is doing **_the thing_**.

Here are the details:
|Attribute|Value|Notes|
|----|----|---|
|SessionID|06d792f7-028b-4371-866c-88f9916ad3c5||
|AppServer|KrakenServer||
|Charset|Unicode (UTF-8)|
|Connected|true|This should be `false` 😝|
|Connection|Upgrade||
|Cookies|{none}|None expected|
|CurrentCommand|getAssetsList||
|CurrentToken|{null}||
|Handshaked|true||
|Host|socket.fleetfreedom.com||
|HttpVersion|HTTP/1.1||
|InClosing|true|That's interesting...|
|LastActiveTime|2021-02-08 19:22:53.880|Current time at time of reading logs was `2021-02-08 21:06:48.547`, with `clearIdleSessionInterval="300"` and `idleSessionTimeOut="300"`; almost 2 hours.|
|LocalEndPoint|&lt;redacted&gt;||
|Method|GET|
|Origin|https://v4.fleetfreedom.com||
|Path|/?ghostId=&lt;redacted&gt;|`ghostId` is the user's session id|
|PrevCommand|1|Not sue why this is `1` as all my commands are named.|
|RemoteEndPoint|&lt;redacted&gt;||
|SecWebSocketProtocol|||
|SecWebSocketVersion|13||
|SecureProtocol|Tls12||
|StartTime|2021-02-08 19:14:34.910||
|SubProtocol|Basic||
|Upgrade|websocket||
|UriScheme|wss||

My last suspicion was that one of my customers with their own code is dong something weird while trying to use the websocket instead of the RESTful service.  However, this is a regular customer, and it looks like they're using Chrome based on the analytics. So at this point I am at a loss.

I've enlisted the help of another dev and hopefully she'll be able to see where things are getting hung up, or will begin work on the transition to .NET5...

**Comment by mithiladeniese** [comment]
I am a developer working with @AlexLein on the handle leak issue we are facing. So far I have found out that the leaking handles are in fact "event handles".
![image](https://user-images.githubusercontent.com/80304008/110418965-671e7180-8066-11eb-9928-ed92b66d20b8.png)
We are still trying to figure out which events are causing the leak.

**Comment by chucklu** [comment]
@mithiladeniese Have you tried tools like CLR Profiler？
