### ISSUE TITLE
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by shawnlxl** [kerryjiang/SuperSocket#444]
版本：SuperSocket 2.0.0-beta7
问题：程序运行3、4天就会出现一次
配置：
`"serverOptions": {
    "name": "Server",
    "receiveTimeout": 60000,
    "sendTimeout": 60000,
    "listeners": [
      {
        "ip": "Any",
        "port": "502"
      }
    ]
  }`
日志：
```
2020-11-28 10:30:02.606 +08:00 [INF] SessionID：6f321b36-3fb5-4ae0-a955-82c7e6d8792e 上报时间：2020-11-28 10:30:02 温度：18.5 湿度：41.8  信号强度：145

2020-11-28 10:35:12.607 +08:00 [ERR] Exception happened in ReceiveAsync
System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at SuperSocket.Channel.TcpPipeChannel`1.ReceiveAsync(Socket socket, Memory`1 memory, SocketFlags socketFlags, CancellationToken cancellationToken)
   at SuperSocket.Channel.TcpPipeChannel`1.FillPipeWithDataAsync(Memory`1 memory, CancellationToken cancellationToken)
   at SuperSocket.Channel.PipeChannel`1.FillPipeAsync(PipeWriter writer)

2020-11-28 10:35:12.747 +08:00 [INF] The session disconnected: 6f321b36-3fb5-4ae0-a955-82c7e6d8792e (SocketError)

```

**Comment by kerryjiang** [comment]
连接非正常断开的意思。
