### ISSUE TITLE
Unhandled exception causes application crash

### ISSUE THREAD

**Issue by martinmine** [kerryjiang/SuperSocket#470]
After upgrading from beta7 to beta.8, I can see the following unhandled exception crashing my application:
```
An existing connection was forcibly closed by the remote host. System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at SuperSocket.Channel.TcpPipeChannel`1.Close()
   at SuperSocket.Channel.PipeChannel`1.HandleClosing()
   at SuperSocket.Channel.PipeChannel`1.WaitHandleClosing()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by martinmine** [comment]
Should be resolved by https://github.com/kerryjiang/SuperSocket/commit/1ea8aff4a369d562463b90bd5dd2e598f5d566a0
