### ISSUE TITLE
js 连接websocket时出错

### ISSUE THREAD

**Issue by 42805578** [kerryjiang/SuperSocket#481]
我的SuperSocket.WebSocket运行在windows service,然后在js去连接这个socket server,但出现下面的错误信息

ERROR WebSocketServer-9029417 - Session: 91e911b4-45c8-4d3a-8777-5235cfb8d076/172.21.36.5:63483
Unexpected error
Caller: OnBeginInitStream, file path: d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncStreamSocketSession.cs, line number: 255
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: An unknown error occurred while processing the certificate
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at SuperSocket.SocketEngine.AsyncStreamSocketSession.OnBeginInitStream(IAsyncResult result, Boolean connect)

**Comment by kerryjiang** [comment]
这个error看起来和证书有关吧
