### ISSUE TITLE
fail: TcpChannelCreator[0] Failed to create channel for Authentication failed

### ISSUE THREAD

**Issue by NaderHamzeiGMAIL** [kerryjiang/SuperSocket#497]
Hello,

I am trying to migrate my old SuperWebSockets tp SuperSoocket.WebSocket.Server. 
We can connect using ws and the non SSL port. however, on upgrade portion of handshake there is disconnect from the browser (Chrome) as websockets need SSL now.
When we try to connect using wss, we get the following error:

`fail: TcpChannelCreator[0]
      Failed to create channel for 127.0.0.1:58992.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at SuperSocket.Server.TcpChannelCreatorFactory.<>c__DisplayClass3_0`1.<<CreateChannelCreator>b__1>d.MoveNext() in C:\Users\nader\Documents\SuperSockets\SuperSocket-master\src\SuperSocket.Server\TcpChannelCreatorFactory.cs:line 116
--- End of stack trace from previous location ---
   at SuperSocket.Server.TcpChannelCreator.OnNewClientAccept(Socket socket) in C:\Users\nader\Documents\SuperSockets\SuperSocket-master\src\SuperSocket.Server\TcpChannelCreator.cs:line 114`

I've searched online and found others using Supersockets with same issues. I tried any advice that was there but still the same error.

I did create my own localhost cert. and that didn't work, I also created a cert using Kerry's CertificateCreator and that also didn't work. the name was named to 'localhost' with 'supersocket.pfx' as file name and password equal to 'supersockets' for testing. still no luck.

I have also gone into chrome://flags/#allow-insecure-localhost and enabled "Allow invalid certificates for resource loaded from localhost' but still the same error

We have the cert info in app.settings and also in Program.cs hostbuilder

`         .ConfigureSuperSocket(options =>
            {
                options.AddListener(new ListenOptions
                {
                    Security = System.Security.Authentication.SslProtocols.Tls12,
                    Port = 8080,
                    Ip = "Any",
                    CertificateOptions = new CertificateOptions
                    {
                        Certificate = new System.Security.Cryptography.X509Certificates.X509Certificate("supersocket.pfx", "supersocket")
                    }
                });
            })`

While debugging we did see that the cert if loaded but for some reason it just does seem to accept the cert.

Any ideas?

**Comment by kerryjiang** [comment]
What kind of url you use to connect the websocket server in browser?

**Comment by NaderHamzeiGMAIL** [comment]
wss://localhost:8080 is the URl

and this is from program.cs:
.ConfigureSuperSocket(options =>
            {
                options.AddListener(new ListenOptions
                {
                    Security = System.Security.Authentication.SslProtocols.Tls12,
                    Port = 8080,
                    Ip = "Any",
                    CertificateOptions = new CertificateOptions
                    {
                        Certificate = new System.Security.Cryptography.X509Certificates.X509Certificate("supersocket.pfx", "supersocket")
                    }
                });
            })

**Comment by kerryjiang** [comment]
What's the CN of the certificate you use?

**Comment by NaderHamzeiGMAIL** [comment]
do you mean common name? localhost
I used your CertCreator as well

**Comment by kerryjiang** [comment]
Oh, could you install the self-signed certificate in your local trust certificate store?

**Comment by NaderHamzeiGMAIL** [comment]
Hi Kerry,
I tried that and it still didn't work. Same error

**Comment by NaderHamzeiGMAIL** [comment]
This issue is still open
I still seem to having an  issue with SuperSockert and the pfx cert.
Does anyone know how to resolve this?
