### ISSUE TITLE
The test case TestDetachableChannel doesn't work sometime

### ISSUE THREAD

**Issue by kerryjiang** [kerryjiang/SuperSocket#528]
https://github.com/kerryjiang/SuperSocket/runs/3469981170#step:8:8700

Error Message:
   System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'SuperSocket.Tests.DerivedNetworkStream'.
  Stack Trace:
     at System.Net.Sockets.NetworkStream.<ThrowIfDisposed>g__ThrowObjectDisposedException|63_0()
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken)
   at SuperSocket.Tests.ClientTest.TestDetachableChannel(Type hostConfiguratorType) in D:\a\SuperSocket\SuperSocket\test\SuperSocket.Tests\ClientTest.cs:line 288
--- End of stack trace from previous location ---
  Standard Output Messages:
 Server started.
 Before DetachAsync

**Comment by kerryjiang** [comment]
Never see this error for a while.
