### ISSUE TITLE
我在尝试client ReceiveAsync() 时尝试wait 发生异常，如何处理

### ISSUE THREAD

**Issue by notcaremath** [kerryjiang/SuperSocket#541]
var t = client.ReceiveAsync().AsTask();
 t.Wait(TimeSpan.FromSeconds(1));引发异常；
2021-11-25 09:12:32,876 [9] DEBUG ConsoleApp.Program [(null)] - System.AggregateException: One or more errors occurred. (Operation is not valid due to the current state of the object.)
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SuperSocket.Channel.DefaultObjectPipe`1.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(Int16 token) in D:\\SuperSocket-master\src\SuperSocket.Channel\DefaultObjectPipe.cs:line 168
   at SuperSocket.Channel.PipeChannel`1.RunAsync()+MoveNext() in D:\\SuperSocket-master\src\SuperSocket.Channel\PipeChannel.cs:line 89
   at SuperSocket.Channel.PipeChannel`1.RunAsync()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SuperSocket.Channel.Extensions.ReceiveAsync[TPackageInfo](IAsyncEnumerator`1 packageStream) in D:\\SuperSocket-master\src\SuperSocket.Channel\Extensions.cs:line 18
   at SuperSocket.Client.EasyClient`1.ReceiveAsync() in D:\\SuperSocket-master\src\SuperSocket.Client\EasyClient.cs:line 226
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)

**Comment by notcaremath** [comment]
![image](https://user-images.githubusercontent.com/49631761/143508916-ebd9556c-ea2a-42ed-9a40-cff6679d5ee9.png)
假如调用者 valueTask.AsTask().wait(timespan.from...(1000)).  getResult(token)会引发异常，是不是应该约束一下，使程序健全
