### ISSUE TITLE
Switch to TLS in an active session

### ISSUE THREAD

**Issue by tinohager** [kerryjiang/SuperSocket#56]
Hi
I want add TLS support to my smtp server project. A smtp session starts without TLS and after the command "STARTTLS" the session switch to TLS.

I test with the following code, but this not work

```
#Config
var config = new SuperSocket.SocketBase.Config.ServerConfig();
config.Certificate = new SuperSocket.SocketBase.Config.CertificateConfig() { FilePath = "test.pfx", Password = "test" };

#Session receive "STARTTLS" command (public class SmtpSession : AppSession<SmtpSession>)
this.SecureProtocol = System.Security.Authentication.SslProtocols.Tls;
```

I found a other example (not use supersocket) this one work
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer/Protocol/StartTlsCommand.cs

```
var stream = new SslStream(context.Text.GetInnerStream(), true);
await stream.AuthenticateAsServerAsync(_certificate, false, SslProtocols.Default, true);
context.Text = new NetworkTextStream(stream);
```

**Comment by kerryjiang** [comment]
Please try to use the AppServer's method "void ResetSessionSecurity(IAppSession session, SslProtocols security)".

**Comment by tinohager** [comment]
Sorry for the late answer. I was on a conference the last days.

I try with the ResetSessionSecurity method, but the mail library throws a exception.

> Socket connection has been refused by remote host. InnerException message follows: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. InnerException message follows: An existing connection was forcibly closed by the remote host ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at a.ae.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)

**Comment by kerryjiang** [comment]
Where did this exception come from? Was it from SuperSocket?

**Comment by tinohager** [comment]
No the exception throws the mailbee library, is my test framework. (https://www.nuget.org/packages/MailBee.NET)

Here a simple Example of the Mailserver
```cs
    class Program
    {
        static void Main(string[] args)
        {
            var example = new Example();
            example.Start();

            Console.WriteLine("Mailserver started");
            Console.ReadLine();
        }   
    }
```


```cs
    public class Example
    {
        private MailServer _mailServer;

        public void Start()
        {
            //Only need visual studio copy the SocketEngine.dll
            var configuration = new SuperSocket.SocketEngine.Configuration.Server();

            //Configuration
            var config = new SuperSocket.SocketBase.Config.ServerConfig();
            config.Port = 25;
            config.MaxConnectionNumber = 10;
            config.ClearIdleSession = true;
            config.ClearIdleSessionInterval = 60; //seconds
            config.IdleSessionTimeOut = 60;
            config.MaxRequestLength = 2097152; //2MB
            config.ListenBacklog = 5; //Waiting Connection Pool
            config.SendBufferSize = 1024;
            config.ReceiveBufferSize = 1024;
            config.SyncSend = true;
            config.LogBasicSessionActivity = false;

            this._mailServer = new MailServer();
            this._mailServer.NewRequestReceived += new RequestHandler<SmtpSession, StringRequestInfo>(NewRequestReceived);

            this._mailServer.Setup(config);
            this._mailServer.Start();
        }

        private void NewRequestReceived(SmtpSession session, StringRequestInfo requestInfo)
        {
            session.ProccessRequest(requestInfo.Key, requestInfo.Body);
        }

        public class MailServer : AppServer<SmtpSession>
        {
            public MailServer() : base(new CommandLineReceiveFilterFactory(Encoding.UTF8, new MailCommandParser()))
            {
            }
        }

        public class SmtpSession : AppSession<SmtpSession>
        {
            private bool _readyForData;

            protected override void OnSessionStarted()
            {
                Thread.Sleep(20);
                this.Send("220 Mail Service ready");
            }

            public void ProccessRequest(string key, string data)
            {
                if (this._readyForData)
                {
                    if (!String.IsNullOrEmpty(key))
                    {
                        this.DataRequest(key);
                        return;
                    }
                    this.DataRequest(data);
                }
                else
                {
                    this.CommandRequest(key, data);
                }
            }

            private void CommandRequest(string key, string data)
            {
                switch (key.ToUpper())
                {
                    case "EHLO":
                        this.Send("250-Hello");
                        this.Send("250-STARTTLS");
                        this.Send("250 OK");
                        return;
                    case "HELO":
                        this.Send("250 Hello");
                        return;
                    case "RSET":
                        this.Send("250 Ok");
                        return;
                    case "NOOP":
                        this.Send("250 Ok");
                        return;
                    case "STARTTLS":
                        //Switch in TLS Session
                        this.Send("220 Ready to start TLS");
                        this.AppServer.ResetSessionSecurity(this, System.Security.Authentication.SslProtocols.Default);
                        return;
                    case "MAIL FROM":
                        this.Send("250 Sender ok");
                        return;
                    case "RCPT TO":
                        this.Send("250 Recipient ok");
                        return;
                    case "DATA":
                        this._readyForData = true;
                        this.Send("354 Go ahead, make my day");
                        return;
                    case "QUIT":
                        this.Send("221 Closing");
                        Thread.Sleep(20);
                        this.Close();
                        return;
                }

                this.Send("500 Unrecognized command");
            }

            private void DataRequest(string data)
            {
                #region Receive Data End Char
                if (data.Equals(".", StringComparison.Ordinal))
                {
                    this.Send("250 Queued");
                    this._readyForData = false;
                }
                #endregion
            }
        }

        public class MailCommandParser : IRequestInfoParser<StringRequestInfo>
        {
            public StringRequestInfo ParseRequestInfo(string source)
            {
                if (source.StartsWith("EHLO", StringComparison.OrdinalIgnoreCase))
                {
                    return ParseRequestInfo(source, " ");
                }

                if (source.StartsWith("HELO", StringComparison.OrdinalIgnoreCase))
                {
                    return ParseRequestInfo(source, " ");
                }

                if (source.StartsWith("MAIL FROM", StringComparison.OrdinalIgnoreCase))
                {
                    return ParseRequestInfo(source, ":");
                }

                if (source.StartsWith("RCPT TO", StringComparison.OrdinalIgnoreCase))
                {
                    return ParseRequestInfo(source, ":");
                }

                if (source.StartsWith("DATA", StringComparison.OrdinalIgnoreCase))
                {
                    return new StringRequestInfo(source, String.Empty, null);
                }

                if (source.StartsWith("RSET", StringComparison.OrdinalIgnoreCase))
                {
                    return new StringRequestInfo(source, String.Empty, null);
                }

                if (source.StartsWith("NOOP", StringComparison.OrdinalIgnoreCase))
                {
                    return new StringRequestInfo(source, String.Empty, null);
                }

                if (source.StartsWith("STARTTLS", StringComparison.OrdinalIgnoreCase))
                {
                    return new StringRequestInfo(source, String.Empty, null);
                }

                if (source.StartsWith("QUIT", StringComparison.OrdinalIgnoreCase))
                {
                    return new StringRequestInfo(source, "", null);
                }

                return new StringRequestInfo(String.Empty, source, null);
            }

            private StringRequestInfo ParseRequestInfo(string source, string spliter)
            {
                var pos = source.IndexOf(spliter);

                var name = String.Empty;
                var param = String.Empty;

                if (pos > 0)
                {
                    name = source.Substring(0, pos);
                    param = source.Substring(pos + 1);
                }
                else
                {
                    name = source;
                }

                return new StringRequestInfo(name, param.Trim(), null);
            }
        }
    }
```

**Comment by kerryjiang** [comment]
Can I have a full stack trace of that exception?

I cannot find where that exception from by the text you posted.

**Comment by tinohager** [comment]
This is the client, if you change the "EnableSsl" to false it works, but with true not.

```cs
        static void Main(string[] args)
        {
            CreateTestMessage("localhost");
            Console.ReadLine();
        }

        public static void CreateTestMessage(string server)
        {
            try
            {
                var from = "ben@contoso.com";
                var to = "jane@contoso.com";
                var message = new MailMessage(from, to);
                message.Subject = "Using the new SMTP client.";
                message.Body = @"Using this new feature, you can send an e-mail message from an application very easily.";
                var client = new SmtpClient(server);
                client.EnableSsl = true;
                client.Send(message);
                Console.WriteLine("Send mail successful");
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.Message);
            }
        }
```

**Comment by tinohager** [comment]
I hope with this 2 examples you can follow my problem?

**Comment by kerryjiang** [comment]
Do you mean the exception you mentioned was thrown from the client side?

**Comment by tinohager** [comment]
Yes the client throw this exception. But the demo client i post here use the .net framework classes. In my private client i use the mailbee library but this need a licence...

**Comment by kerryjiang** [comment]
Could you check the logs of the server side to see what happened?

**Comment by tinohager** [comment]
i have add log4net in my demo server project.

> 2016-06-23 18:02:32,351 [9] INFO  MailServer-62476613 - The server instance MailServer-62476613 has been started!

**Comment by kerryjiang** [comment]
Check the error log file.

**Comment by tinohager** [comment]
err.log is emtpy, if it possible ResetSessionSecurity close the current connection instead update to TLS

**Comment by kerryjiang** [comment]
Could you debug the method ResetSessionSecurity to see what happen?
Probably the client try to connect the secure port 465 of the smtp server.
https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol

**Comment by tinohager** [comment]
I have check this possibility with the port 465, with my reference project (https://github.com/cosullivan/SmtpServer) here also only port 25 is open and it works fine.

```cs
            var options = new OptionsBuilder()
                .ServerName("SmtpServer SampleApp")
                .Port(25)
                .MessageStore(new ConsoleMessageStore())
                .MailboxFilter(new ConsoleMailboxFilter())
                .Certificate(new System.Security.Cryptography.X509Certificates.X509Certificate("test.pfx", "test"))
                .Build();
```

**Comment by tinohager** [comment]
i found a exception but if not available in the log file...

AsyncStreamSocketSession -> OnSessionStarting
System.NullReferenceException: Object reference not set to an instance to an object

**Comment by kerryjiang** [comment]
Could you debug the method ResetSessionSecurity to see what happen?

**Comment by tinohager** [comment]
on this position i have the exception
-> m_Stream.BeginRead(m_ReadBuffer, m_Offset, m_Length, OnStreamEndRead, m_Stream);

**Comment by tinohager** [comment]
Can you reproduce the exception?

**Comment by kerryjiang** [comment]
Yes, I found it.
But it is very difficult to fix in this version.
