### ISSUE TITLE
Unable to use https with SuperSocket.WebSocket

### ISSUE THREAD

**Issue by aliahaider** [kerryjiang/SuperSocket#572]
This works fine with http but does not with https. I see no exception or error in the logs.
All I see is that a new session was connected:

2022-05-16 15:49:08,666 [6] INFO  SuperWebSocket [PID:7308] (:0) - Session: 56787699-c128-40c9-a08e-b63cb00dd196/10.16.9.95:57270
A new session connected!
and then it was closed by the client.
2022-05-16 15:49:38,654 [12] INFO  SuperWebSocket [PID:7308] (:0) - Session: 56787699-c128-40c9-a08e-b63cb00dd196/10.16.9.95:57270
This session was closed for ClientClosing!

Http and Https both were working before and then it suddenly stopped working for https. Even with TLS 1.2 configured and with ClientMinKeyBitLength(0x00000200) configured for 
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman. 

I have seen stuff online that says after some MS update  this has stopped working.
Any idea or pointer as to what is needed to make it work?

Is there any config needed for SuperSocket.WebSocket for TLS 1.2 or SSL/HTTPS?

Thanks!

**Comment by aliahaider** [comment]
What I find is that socketServer_NewMessageReceived is not being called when HTTPS is used.
I have set breakpoints in my code for the following event handlers: 
socketServer_NewMessageReceived(WebSocketSession session, string e)
private void socketServer_NewSessionConnected(WebSocketSession session)
socketServer_SessionClosed(WebSocketSession session, CloseReason reason)

But when I try to connect to the server using https I only see this being called:
socketServer_SessionClosed(WebSocketSession session, CloseReason reason)

Though there is a log for a session connected &  there is one for session being closed as I have mentioned earlier:
2022-05-16 15:49:08,666 [6] INFO SuperWebSocket [PID:7308] (:0) - Session: 56787699-c128-40c9-a08e-b63cb00dd196/10.16.9.95:57270
A new session connected!
and then it was closed by the client.
2022-05-16 15:49:38,654 [12] INFO SuperWebSocket [PID:7308] (:0) - Session: 56787699-c128-40c9-a08e-b63cb00dd196/10.16.9.95:57270
This session was closed for ClientClosing!

So I am not sure why the receive event handler is not being called.
I see no exception thrown etc.

**Comment by kerryjiang** [comment]
Try 
···
config.Security = "Tls12";
···

**Comment by aliahaider** [comment]
I changed the config to enable TLS12 in my config websocket:
<servers>
      <server name="SuperWebSocket" serviceName="SuperWebSocket" ip="Any" port="XXXX" Security="Tls12" 

But using SuperWebSocket.dll 0.6.0.0 I see the following failure:
2022-06-16 17:04:14,371 [9936] INFO  SuperWebSocket [PID:8332] (:0) - Session: 1b1f1c92-5b3a-4803-b0ea-a7b80d2dab98/10.16.9.5:63280
New SocketSession was accepted!
2022-06-16 17:04:14,417 [8652] ERROR SuperWebSocket [PID:8332] (:0) - System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.SocketEngine.AsyncStreamSocketSession`2.OnBeginInitStream(IAsyncResult result)
2022-06-16 17:04:14,423 [8652] INFO  SuperWebSocket [PID:8332] (:0) - Session: 1b1f1c92-5b3a-4803-b0ea-a7b80d2dab98/10.16.9.5:63280
This session was closed!
2022-06-16 17:04:14,427 [8652] INFO  SuperWebSocket [PID:8332] (:0) - Session: 9944915f-d491-4df4-ab5c-d15d29a65e80/10.16.9.5:63281
New SocketSession was accepted!
2022-06-16 17:04:14,441 [9936] ERROR SuperWebSocket [PID:8332] (:0) - System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.SocketEngine.AsyncStreamSocketSession`2.OnBeginInitStream(IAsyncResult result)
2022-06-16 17:04:14,442 [9936] INFO  SuperWebSocket [PID:8332] (:0) - Session: 9944915f-d491-4df4-ab5c-d15d29a65e80/10.16.9.5:63281
This session was closed!


and with SuperSocket.WebSocket.dll  1.6.6.1 I see the following:
A new session connected!
This session was closed for ClientClosing!

**Comment by aliahaider** [comment]
Hi Kerry:  
Do you have any other pointer or suggestion as how to resolve this issue? When I try to connect with https I get this "Websocket Server temporarily unavailable, please try later" on the browser.

But in the supersocket.websocket logs I do see: 
2022-08-24 16:05:43,406 [6] INFO  SuperWebSocket [PID:11216] (:0) - Session: 2d84b50e-2b7d-4173-9920-b5c9fa1a126d/10.16.8.185:53590
A new session connected!
and then I see nothing until I close the browser.
This log is coming from the supersocket.websocket.dll or one of the other supersocket dlls.

After I close the browser I see this log:
2022-08-24 16:06:13,395 [11] INFO  SuperWebSocket [PID:11216] (:0) - Session: 2d84b50e-2b7d-4173-9920-b5c9fa1a126d/10.16.8.185:53590
This session was closed for ClientClosing!

Thanks!

**Comment by aliahaider** [comment]
With the older version of superwebsocket I see this error when using https:
2022-08-24 16:49:50,884 [1936] ERROR SuperWebSocket [PID:10348] (:0) - System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.SocketEngine.AsyncStreamSocketSession`2.OnBeginInitStream(IAsyncResult result)
2022-08-24 16:49:50,888 [9280] ERROR SuperWebSocket [PID:10348] (:0) - System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.SocketEngine.AsyncStreamSocketSession`2.OnBeginInitStream(IAsyncResult result)

**Comment by aliahaider** [comment]
Hi Kerry:
What does this message mean:
This session was closed for ServerClosing!

When I use https I see the new session gets connected then I receive a few messages then suddenly I see this message pops up. I am trying to understand what this message means. 
After this message I see again a log that says a new session got connected.
That is the seq:
2022-10-05 16:58:42,818 [6] INFO  SuperWebSocket [PID:5520] (:0) - Session: c7eec147-b710-4fe3-ab04-3cb6b168b774/10.16.9.95:64743
A new session connected!
2022-10-05 16:58:42,860 [24] DEBUG [PID:5520] (:0) - new msg arrived session c7eec147-b710-4fe3-ab04-3cb6b168b774
2022-10-05 16:58:42,965 [6] DEBUG  [PID:5520] (:0) - new msg arrived session c7eec147-b710-4fe3-ab04-3cb6b168b774
2022-10-05 16:58:43,024 [4] DEBUG WebSocket.WebSocketHandler [PID:5520] (:0) - dequeued and handled msg
2022-10-05 16:58:43,034 [4] DEBUG WebSocketHandler [PID:5520] (:0) - dequeued and handled msg
2022-10-05 16:58:43,037 [24] INFO  SuperWebSocket [PID:5520] (:0) - Session: c7eec147-b710-4fe3-ab04-3cb6b168b774/10.16.9.95:64743
This session was closed for ServerClosing!
2022-10-05 16:58:43,116 [6] INFO  SuperWebSocket [PID:5520] (:0) - Session: 082b7c9a-58b8-4f5e-8b92-278e2cbe8b7a/10.16.9.95:64745
A new session connected!

**Comment by aliahaider** [comment]
I was able to make it work with version 1.6.6.1 with some registry changes plus config changes and code changes.
