### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by taewoo0282** [kerryjiang/SuperSocket#641]
Version 1.6

The program exits with the corresponding error. I don't know why.
It's not easy to know because it's not an exception in my content.

System.Exception:    at SuperSocket.SocketEngine.AsyncSocketSession.OnSendingCompleted(Object sender, SocketAsyncEventArgs e) in SuperSocket-1.6\SocketEngine\AsyncSocketSession.cs:line 88

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[], Int32, Int32)
   at SuperSocket.SocketEngine.AsyncSocketSession.ClearPrevSendState(System.Net.Sockets.SocketAsyncEventArgs)
   at SuperSocket.SocketEngine.AsyncSocketSession.OnSendingCompleted(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by kerryjiang** [comment]
We don't maintain 1.6 anymore. Could you upgrade to 2.0?
