### ISSUE TITLE
SuperSocket.Client's ConnetAsync function got a System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by Akira3Chou** [kerryjiang/SuperSocket#654]
我在连接到一个本地服务器时，发生了如下异常
![01_ExceptionOccur](https://github.com/kerryjiang/SuperSocket/assets/94149397/c9b203dd-aa09-45d3-93c7-00dfc0c61cc1)

当我尝试进行调试，发现问题出现在这里
![02_DebugTheCode](https://github.com/kerryjiang/SuperSocket/assets/94149397/adaf0e3b-ed28-4582-9c38-4e567bd8aa49)

当我在查找资料时，发现这里有类似的问题，https://github.com/shadowsocks/shadowsocks-windows/issues/476
我根据这个issue的建议执行netsh winsock reset命令
![03_ExecuteTheResetCmd](https://github.com/kerryjiang/SuperSocket/assets/94149397/91cc18c6-4714-4dc4-b9d5-d11f5b16fe55)

reset命令执行完毕后，这里的问题解决了，但是我本地启动的Socket服务器无法启动了。
![04_DebugTheCodeAfterResetCmd](https://github.com/kerryjiang/SuperSocket/assets/94149397/44357ccf-2eda-43e0-9e7d-b197055e6707)

有人遇到和我类似的状况嘛？顺便提一句，我这边是公司内网环境，在windows域中，并且本机网卡更换过。不知道是不是和环境有关。

**Comment by Akira3Chou** [comment]
日志打印异常详细：
System.Net.Sockets.SocketException (10014): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.get_RemoteEndPoint()
   at SuperSocket.Client.ConnectState.CreateChannel[TReceivePackage](IPipelineFilter`1 pipelineFilter, ChannelOptions channelOptions)
   at SuperSocket.Client.ConnetAsync(EndPoint remoteEndPoint, CancellationToken cancellationToken)

**Comment by wj8400684** [comment]
这应该跟supersocket没有关系，你随便写个socket应该也是报这个错误！

**Comment by Akira3Chou** [comment]
> 这应该跟supersocket没有关系，你随便写个socket应该也是报这个错误！

这个问题的根源不在SuperSocket，但是其他的socket客户端都正常在工作，因为没有访问socket.RemoteEndPoint。我把这句注释掉了，SuperSocket一样也正常工作
