### ISSUE TITLE
Exception happened in SendAsync

### ISSUE THREAD

**Issue by Z5SteveKim** [kerryjiang/SuperSocket#655]
fail: IChannel[0]
      Exception happened in SendAsync
      System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at SuperSocket.Channel.TcpPipeChannel`1.SendOverIOAsync(ReadOnlySequence`1 buffer, CancellationToken cancellationToken) in TcpPipeChannel.cs:line 75
         at SuperSocket.Channel.PipeChannel`1.ProcessOutputRead(PipeReader reader, CancellationTokenSource cts) in PipeChannel.cs:line 278

**Comment by kerryjiang** [comment]
Normal connection abort by the remove client. Should be ignored.

**Comment by kerryjiang** [comment]
Made a change to ignore it:
https://github.com/kerryjiang/SuperSocket/commit/f4f5dcaeffba3cbf1609ea167b4b18c8232f166a
