### ISSUE TITLE
TCP Socket Occasional error when receiving data

### ISSUE THREAD

**Issue by wanmen4580** [kerryjiang/SuperSocket#660]
When I am continuously receiving client data, occasional errors are reported
Version：.17 beta
SuperSocketService[0]
      Failed to handle the session b0435c35-87a8-4227-9a7a-563196b9e08f.
      System.InvalidOperationException: Operation is not valid due to the current state of the object.
         at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
         at SuperSocket.Channel.DefaultObjectPipeWithSupplyControl`1.SetTaskCompleted(Boolean result)
         at SuperSocket.Channel.DefaultObjectPipe`1.ReadAsync()
         at SuperSocket.Channel.PipeChannel`1.RunAsync()+MoveNext()
         at SuperSocket.Channel.PipeChannel`1.RunAsync()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at SuperSocket.Server.SuperSocketService`1.HandleSession(AppSession session, IChannel channel)
         at SuperSocket.Server.SuperSocketService`1.HandleSession(AppSession session, IChannel channel)

**Comment by kerryjiang** [comment]
Haven't seen this error for a while. Mark it as solved.
