### ISSUE TITLE
SuperSocket on azure

### ISSUE THREAD

**Issue by henriqueleandro** [kerryjiang/SuperSocket#67]
you have some example of the updated azure, the example that has the various errors when running.

**Comment by kerryjiang** [comment]
Thanks for the remind, I'll update the sample.

BTW, the general idea of it is binding the port number to the dynamic real internal port.

**Comment by henriqueleandro** [comment]
thank you.

it's an error on the line
if (! m_Bootstrap.Initialize (RoleEnvironment.CurrentRoleInstance.InstanceEndpoints.ToDictionary (p => p.Key, p => p.Value.IPEndpoint)))
             {

most will expect you to update the code.
You can tell me here when you finish please update?

:+1:

**Comment by kerryjiang** [comment]
Did you catch the exception? Can you get the stacktrace of this error?
Did you find some information in the log files?

**Comment by henriqueleandro** [comment]
Could not load file or assembly 'log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The system cannot find the file specified.

   at SuperSocket.SocketBase.Logging.Log4NetLogFactory..ctor(String log4netConfig)
   at SuperSocket.SocketBase.Logging.Log4NetLogFactory..ctor() in F:\SuperSocket-1.6.4\SocketBase\Logging\Log4NetLogFactory.cs:line 21

**Comment by kerryjiang** [comment]
As the error message, the required assembly log4net was not deployed.

**Comment by henriqueleandro** [comment]
performed place, prem in azure when you publish will not go take another look at the logs, the new version of azure you did it work?

att.
