### ISSUE TITLE
SuperSocket.WebScoket.Server，使用wss，采用Tls12时，报错

### ISSUE THREAD

**Issue by lovefather** [kerryjiang/SuperSocket#742]
客户端每次重连的时候就会报如下错误

info: SuperSocketService[0]
      The listener [Ip=any, Port=8080, Security=Tls12, Path=, BackLog=0, NoDelay=False] has been started.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\Code\Github\lovefather\GW\GWApp\GW.LivesServer\bin\Debug\net8.0
fail: IConnection[0]
      Exception happened in ReceiveAsync
      System.IO.IOException: The decryption operation failed, see inner exception.
       ---> System.ComponentModel.Win32Exception (0x80090327): 处理证书时，出现了一个未知错误。
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at SuperSocket.Connection.StreamPipeConnection.FillPipeWithDataAsync(Memory`1 memory, CancellationToken cancellationToken)
         at SuperSocket.Connection.PipeConnection.FillPipeAsync(PipeWriter writer, ISupplyController supplyController, CancellationToken cancellationToken)

![image](https://github.com/user-attachments/assets/fbfc031d-1a14-47f9-833a-737f21db222b)

配置代码如下：
`C#
builder.ConfigureSuperSocket(options =>
{
    options.Name = "vtool.com.cn";

    options.AddListener(new ListenOptions()
    {
        Ip = "any",
        Port = 8080,
        Security = SslProtocols.Tls12,
        CertificateOptions = new CertificateOptions()
        {
            FilePath = "vtool.com.cn.pfx",
            Password = "4gx3gatr"
        }
    });
});
`
证书是从阿里云生成的个人免费SSL证书，密码没问题，验证过
![image](https://github.com/user-attachments/assets/9d89521b-2bff-4945-9ebf-11853520d0af)

请问可能是什么原因导致的

**Comment by kerryjiang** [comment]
启动正常，与客户端通信时出错。你把证书在certmgr里面打开看看？

**Comment by dodu2014** [comment]
也遇到同样问题

**Comment by freefer** [comment]
<img width="960" height="480" alt="Image" src="https://github.com/user-attachments/assets/43f38a4a-0080-41b9-b12d-759e79c9861b" />

<img width="1673" height="476" alt="Image" src="https://github.com/user-attachments/assets/f1ffb9dd-f246-474e-bea8-a0ce823c4e70" />
使用wss 还有需要其他设置什么吗

**Comment by freefer** [comment]
使用mkcert-v1.4.4-windows-amd64.exe 生成的证书可以运行
以下是我的使用方式
https://github.com/FiloSottile/mkcert/releases/tag/v1.4.4
cmd:
 mkcert-v1.4.4-windows-amd64.exe -install
 mkcert-v1.4.4-windows-amd64.exe 192.168.2.138
 openssl pkcs12 -export -out certificate.pfx -inkey 192.168.2.138-key.pem -in 192.168.2.138.pem -certfile 192.168.2.138.pem
 openssl pkcs12 -export -out 192.168.2.138.pfx -inkey 192.168.2.138-key.pem -in 192.168.2.138.pem -passout pass:123456
 
<img width="1506" height="892" alt="Image" src="https://github.com/user-attachments/assets/1dd84438-84d5-4daa-8816-68c51a4eecbb" />

<img width="1252" height="563" alt="Image" src="https://github.com/user-attachments/assets/0813687b-7970-4a30-a121-8e34cdd89159" />
