### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by wenqingqiu** [kerryjiang/SuperSocket#761]
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
         at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
         at System.GC.<AllocateUninitializedArray>g__AllocateNewUninitializedArray|66_0[T](Int32 length, Boolean pinned)
         at System.Buffers.TlsOverPerCoreLockedStacksArrayPool1.Rent(Int32 minimumLength)
         at System.IO.Pipelines.Pipe.RentMemory(BufferSegment segment, Int32 sizeHint)
         at System.IO.Pipelines.Pipe.AllocateWriteHeadSynchronized(Int32 sizeHint)
         at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
         at SuperSocket.Channel.PipeChannel1.FillPipeAsync(PipeWriter writer, CancellationToken cancellationToken)

报OutOfMemoryException异常，没有比较大的数据传输，文件和图片都是传id，k8s配置是分配了8G内存，物理内存应该是够的，帮分析下原因

**Comment by kerryjiang** [comment]
多少个连接最高峰，每秒钟多少个并发请求？各个命令大体是干什么？

**Comment by wenqingqiu** [comment]
最高300出头session  每秒钟多少个并发请求没有统计，IM项目，都是文本消息，发送图片和文件都是传id SuperSocket版本是2.0.0-beta.18每次出现这个异常日志System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.就发不了消息，重启服务就正常了。之前用2.0.0-beta7版本没出现过这个问题。

**Comment by kerryjiang** [comment]
需要看你们的代码实现，可能与SuperSocket本身无关。
