### ISSUE TITLE
严重bug，远程主机强迫关闭现有连接

### ISSUE THREAD

**Issue by loveyeguo** [kerryjiang/SuperSocket#767]
```
 private async Task KeepAccept(Socket listenSocket)
 {
     while (!_cancellationTokenSource.IsCancellationRequested)
     {
         try
         {
             var client = await listenSocket.AcceptAsync().ConfigureAwait(false);
             OnNewClientAccept(client);
         }
         catch (Exception e)
         {
             if (e is ObjectDisposedException || e is NullReferenceException)
                 break;
             
             if (e is SocketException se)
             {
                 var errorCode = se.ErrorCode;

                 //The listen socket was closed
                 if (errorCode == 125 || errorCode == 89 || errorCode == 995 || errorCode == 10004 || errorCode == 10038)
                 {
                     break;
                 }
             }
             
             _logger.LogError(e, $"Listener[{this.ToString()}] failed to do AcceptAsync");
             continue;
         }
     }

     _stopTaskCompletionSource.TrySetResult(true);
 }
```
在这段代码中，
` var client = await listenSocket.AcceptAsync().ConfigureAwait(false);`
目前大约有几百个tcp客户端在像我tcp服务端发送报文。
日志一直在报：远程主机强迫关闭现有连接，推测是有不合法的客户端一直在断掉重连，在运行几个小时以后，tcp服务端程序无法再接收新的连接。

**Comment by loveyeguo** [comment]
是否在代码
` _logger.LogError(e, $"Listener[{this.ToString()}] failed to do AcceptAsync");`后面，应主动调用：
`  client?.Close();`？

**Comment by loveyeguo** [comment]
重启后又恢复正常，但是过几个小时，客户端又开始无法再次建立新连接。

**Comment by kerryjiang** [comment]
_logger.LogError(e, $"Listener[{this.ToString()}] failed to do AcceptAsync"); 这个记录的什么？你拿到了没有？

**Comment by loveyeguo** [comment]
以下是报错的详细内容： 然后几个小时后，后续客户端已经无法再建立新连接
```
[2024-12-13 15:56:30.184028 +08:00]-[fail]: TcpChannelCreator[0]-[threed:6]
     Connection reset by remote client: ****************************异常文本****************************
     【出现时间】：2024/12/13 15:56:30
     【异常类型】：SocketException
     【异常信息】：远程主机强迫关闭了一个现有的连接。
     【堆栈调用】：   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
        at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
     --- End of stack trace from previous location ---
        at SuperSocket.Server.TcpChannelCreator.KeepAccept(Socket listenSocket) in D:\coding\夏工\code\SuperSocket-master\src\SuperSocket.Server\TcpChannelCreator.cs:line 103
     ***************************************************************

[2024-12-13 15:56:30.185471 +08:00]-[fail]: TcpChannelCreator[0]-[threed:6]
     Connection reset by remote client with IP: 220.248.164.71
[2024-12-13 15:56:40.311129 +08:00]-[fail]: TcpChannelCreator[0]-[threed:13]
     Connection reset by remote client: ****************************异常文本****************************
     【出现时间】：2024/12/13 15:56:40
     【异常类型】：SocketException
     【异常信息】：远程主机强迫关闭了一个现有的连接。
     【堆栈调用】：   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
        at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
     --- End of stack trace from previous location ---
        at SuperSocket.Server.TcpChannelCreator.KeepAccept(Socket listenSocket) in D:\coding\夏工\code\SuperSocket-master\src\SuperSocket.Server\TcpChannelCreator.cs:line 103
```

**Comment by loveyeguo** [comment]
我再完整的描述一下：  如上，我部署了tcp服务端，目前大约有200多个tcp客户端连接。  我同时侦听了1799,1800端口。 经测试，如上错误一直在报，大概一分钟左右报一次。  持续几个小时后，1799端口已无法再次连接。但是1800端口(此端口为测试端口，目前只有几个tcp客户端连接)是正常可以连接的。  请问出现的原因是什么？  猜测是否有资源未正确释放？

**Comment by loveyeguo** [comment]
请注意，我替换成原来的SuperSocket1.6老版本后，未发现任何报错信息。也没有出现后续客户端无法连接的情况！

**Comment by loveyeguo** [comment]
> _logger.LogError(e, $"Listener[{this.ToString()}] failed to do AcceptAsync"); 这个记录的什么？你拿到了没有？

在线等啊大佬！！！

**Comment by kerryjiang** [comment]
远程主机强迫关闭了一个现有的连接? 这个SocketException的ErrorCode是啥？

**Comment by msdn5** [comment]
遇到同样的问题,不过不是一个error,也是在AcceptAsync处抛出的异常,异常日志如下:
`
TcpConnectionListener.MoveNext [0] - : Listener[Ip=Any, Port=5009, AuthenticationOptions=, Path=, BackLog=0, NoDelay=False] failed to do AcceptAsync System.Net.Sockets.SocketException (10044): 在这个地址家族中不存在对指定的插槽类型的支持。
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.AcceptAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AcceptAsync(Socket acceptSocket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AcceptAsync()
   at SuperSocket.Server.Connection.TcpConnectionListener.KeepAccept(Socket listenSocket)

查看代码后发现并没有跳出while (!_cancellationTokenSource.IsCancellationRequested)
一旦此异常被抛出后15毫秒会触发下一次异常循环往复(无法接收新的请求),重启应用恢复正常.
`
环境配置
`
.net8.0
SuperSocket.Server 2.0.2
SuperSocket.Command 2.0.2
`
在发生异常时,我cmd执行了netstat -an,没有大量的端口消耗,本地5009端口也不再处于监听状态(LISTENING).
