### ISSUE TITLE
The sending attempt timed out

### ISSUE THREAD

**Issue by Liuhuifeng** [kerryjiang/SuperSocket#97]
The sending attempt timed out
   at SuperSocket.SocketBase.AppSession`2.InternalSend(ArraySegment`1 segment)
   at SuperSocket.SocketBase.AppSession`2.Send(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.SocketBase.AppSession`2.Send(String message)
   at YLB.Mutil.IMService.WinSession.Send(Object msg) in D:\Project\YaleBao\YLB.Mutil.IMService\App\WinSession.cs:line 98

每隔一两天，一段时间内会出现很多 timed out 异常，大概800个连接数

**Comment by Liuhuifeng** [comment]
<superSocket 
    maxWorkingThreads="30"
    minWorkingThreads="10"
    maxCompletionPortThreads="30"
    minCompletionPortThreads="10">
    <servers>
      <server name="" serverType=""
              ip="Any"
              port="5222"
              listenBacklog="100"
              mode="Tcp"
              textEncoding="UTF-8"
              sendingQueueSize="100"
              receiveBufferSize="512"
              sendBufferSize="512"
              disableSessionSnapshot="true"
              clearIdleSession="true"
              clearIdleSessionInterval="60"
              sendTimeOut="5000"
              idleSessionTimeOut="120"
              maxConnectionNumber="4000">
      </server>

**Comment by a549297336** [comment]
我也遇到了这个问题。。不知道是哪里的错

**Comment by chengwengao** [comment]
这个应该网络不稳定或者服务端socket连接所占用的句柄数被用完等原因造成的，但是supersocket有断线重连机制，你再持续观察一段时间，看这些丢失的连接是否会重新连接。

**Comment by shenzhigang** [comment]
SuperSocket.Websocket 运行一天之后，服务端往客户端发送的时候，出现 “System.TimeoutException: The sending attempt timed out”

**Comment by rayxelloss** [comment]
我也遇到同样的问题，有人解决了吗？

**Comment by chengwengao** [comment]
> 我也遇到同样的问题，有人解决了吗？
试一下这么修改，再持续观察一下：
服务器端设置：
可以修改一下起始端口:
netsh int ipv4 set dynamicport tcp start=2000 num=63000
netsh int ipv4 set dynamicport udp start=2000 num=63000
netsh int ipv6 set dynamicport tcp start=2000 num=63000
netsh int ipv6 set dynamicport udp start=2000 num=63000

然后修改一下注册表缩短time-wait的时间。
regedit打开注册表，添加
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
“MaxUserPort”=dword:0000fffe（65534）
“TcpTimeWaitDelay”=dword:0000005 (缩短为5秒）

**Comment by JyzForCqupt** [comment]
SuperSocket.Websocket 运行一天之后，服务端往客户端发送的时候，出现 “System.TimeoutException: The sending attempt timed out”，同样的问题，有人知道解决办法吗

**Comment by overing** [comment]
https://github.com/kerryjiang/SuperWebSocket/issues/48
